version: '3.9'

services:
  db:
    container_name: drinkstore-db
    image: postgres:13
    restart: always
    ports:
      - 5440:5441
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_drinkstore:/var/lib/postgresql/data
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  db_drinkstore:
